name: Must run on custom runner-acloudguruAAA

on: push

jobs:
  init:
    #runs-on: self-hosted
    runs-on: acloudguruAAA
    steps:
      - run: echo 'hello cloud gurus in runner-acloudguruAAA'
      - run: echo $HOSTNAME
