name: Must run on custom runner-acloudguruAAA

on: push

jobs:
  init:
    #runs-on: self-hosted
    runs-on: acloudguruAAA2
    steps:
      - run: echo 'hello cloud gurus in runner-acloudguruAAA'
      - run: mvn -v
      - run: npm -v
      - run: git -v
      - run: pip -v
      - run: echo $HOSTNAME

