name: Must run on custom runner-acloudguruAAA

on: push

jobs:
  hello_world_job:
    runs-on: wewelabel
    name: A job to say hello
    steps:
    - run: echo $HOSTNAME
    - run: echo hostnamectl
    - run: echo uname -r
    - name: Hello world action step
      id: hello
      uses: actions/hello-world-docker-action@main
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"




